### ISSUE TITLE
INVERT_Y_DIR not declared in HAL.h

### ISSUE THREAD

**Issue by axlspinedoc** [seemecnc/Firmware#11]
The following error comes up when I try to upload the firmware into a Rostock V2. 
The only changes I made were in the Configuration.h tab where I declare that the printer is a Rostock V2.

Arduino: 1.6.13 (Windows 10), Board: "Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

In file included from sketch\HAL.h:77:0,

                 from sketch\Repetier.h:353,

                 from sketch\Commands.cpp:22:

sketch\Printer.h: In static member function 'static void Printer::setYDirection(bool)':

Printer.h:394: error: 'INVERT_Y_DIR' was not declared in this scope

             WRITE(Y_DIR_PIN,!INVERT_Y_DIR);

                              ^

sketch\fastio.h:29:35: note: in definition of macro '_WRITE'

 #define  _WRITE(IO, v)   do { if (v) {DIO ##  IO ## _WPORT |= MASK(DIO ## IO ## _PIN); } else {DIO ##  IO ## _WPORT &= ~MASK(DIO ## IO ## _PIN); }; } while (0)

                                   ^

sketch\Printer.h:394:13: note: in expansion of macro 'WRITE'

             WRITE(Y_DIR_PIN,!INVERT_Y_DIR);

             ^

Printer.h:401: error: 'INVERT_Y_DIR' was not declared in this scope

             WRITE(Y_DIR_PIN,INVERT_Y_DIR);

                             ^

sketch\fastio.h:29:35: note: in definition of macro '_WRITE'

 #define  _WRITE(IO, v)   do { if (v) {DIO ##  IO ## _WPORT |= MASK(DIO ## IO ## _PIN); } else {DIO ##  IO ## _WPORT &= ~MASK(DIO ## IO ## _PIN); }; } while (0)

                                   ^

sketch\Printer.h:401:13: note: in expansion of macro 'WRITE'

             WRITE(Y_DIR_PIN,INVERT_Y_DIR);

             ^

In file included from sketch\Repetier.h:486:0,

                 from sketch\Commands.cpp:22:

sketch\Printer.h: In static member function 'static bool Printer::getYDirection()':

Printer.h:430: error: 'INVERT_Y_DIR' was not declared in this scope

         return((READ(Y_DIR_PIN)!=0) ^ INVERT_Y_DIR);

                                       ^

exit status 1
'INVERT_Y_DIR' was not declared in this scope

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by johnoly99** [comment]
Ahh, good catch!   Issue is fixed in commit 4ab60c0    The #DEFINE was missing for a v2, but it's there now
