### ISSUE TITLE
V2 invert issue

### ISSUE THREAD

**Issue by Slashthedragon** [seemecnc/Firmware#18]
After uploading to my Rostock Max V2 the axes were not driving in the correct direction. 
I edited the setting for directions in the V2 settings and now it drives in the correct direction. I still can't get it level but I am getting closer. As noted elsewhere, you will need to set the Configuration.h for V2 printer and use Arduino 1.0.6 

#define INVERT_X_DIR 0 // was 1
#define INVERT_Y_DIR 0
#define INVERT_Z_DIR 0 // was 1

**Comment by PartDaddy** [comment]
Hi Slashthedragon, 
1. No need to change firmware unless you really want to. 
The official factory response for steppers moving the wrong direction is to turn the plug around at the RAMBo. This reverses the stepper direction without the need to modify firmware. 
2. Arduino 1.6.0
