### ISSUE TITLE
Extruder Motor bug

### ISSUE THREAD

**Issue by junot566** [seemecnc/Firmware#2]
Hello guys 

I was testing the new version REPETIER_VERSION "0.92.2" FIRMWARE_DATE "083116" and I think there is a bug with the extruder motor, for some reason with this version does not work, I have the Kysan or Automation Technology stepper motors and X, Y, Z are working great but E1 does not move at all. 

As soon as I load the previous version back, everything works as normal, I tried this 2 times and I´´m getting the same problem. 

btw, I did the current changes for the Kysan motors. MOTOR_CURRENT {175,175,175,200,0}.
Same problem

As far as I can see there are great features included on this version, really nice work.

regards 

Adrian

**Comment by johnoly99** [comment]
Hmm, @junot566 you say E1, but the default extruder motor for a single extruder is E0.  Double check that, as we are using this firmware exclusively and it's working for us here at the shoP?
