### ISSUE TITLE
Retore Wantai Motor Comment in configuration.h

### ISSUE THREAD

**Issue by loadedsith** [seemecnc/Firmware#4]
My new hotend upgrade had me stumped when the extruder motor started slipping. Eventually I remembered there was a motor change, and that led me to this line in the old firmware.

https://github.com/seemecnc/Repetier-091-ROSTOCKMAX/blob/master/Repetier-091-ROSTOCKMAX/Repetier/Configuration.h#L701 

Line 701 of the old configuration.h says (be sure to scroll, this is very long line): 

```
#define MOTOR_CURRENT {140,140,140,130,0} // Values 0-255 (RAMBO 135 = ~0.75A, 185 = ~1A)  use 140 for xyz and 130 for the E if using Kysan motors and 175 xyz and 200 if using wantai motors
```

Where the new version just says:

```
#define MOTOR_CURRENT {140,140,140,130,0} // Values 0-255 (RAMBO 135 = ~0.75A, 185 = ~1A)  
```

The extra tip here was very helpful after my new hot end firmware update started giving me issues in the extruder motor, could we restore this comment, and possibly add a reminder to the firmware updating docs?

With lots of love!
-g-

**Comment by johnoly99** [comment]
Good point loadedsith,

Added comment back into configuration.h for motor current defs.  See commit #3

**Comment by loadedsith** [comment]
😄
