### ISSUE TITLE
Intermittent Probing Issue

### ISSUE THREAD

**Issue by jjjohnson4112** [seemecnc/Firmware#7]
Reports of probing via the LCD is not functioning correctly. Probing using the GCODE file works fine. 

Issues is not exactly repeatable every time, some times the machine will home and freeze. Other times the machine will home, drop down within Xmm of the bed and freeze. 

Please find and fix bug.

**Comment by johnoly99** [comment]
Fixed in dev branch as of 11/23, will be pushed to master on monday if no reports of other issues
