### ISSUE TITLE
Missing french translation

### ISSUE THREAD

**Issue by Liozon** [seemecnc/Firmware#8]
Hello,
In the uilang.h file, at the line 1261 (https://github.com/seemecnc/Firmware/blob/master/Repetier%20Firmware/Repetier/uilang.h#L1261) the translation for UI_TEXT_ADJTEMPS is missing. The french translation for it is "Ajuster temp".

Thanks! :)
Julien

**Comment by johnoly99** [comment]
Fixed with commit 36b3959

Thanks!
